//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DependenciesvManagerv2
{
    using System;
    using System.Collections.Generic;
    
    public partial class configuration_items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public configuration_items()
        {
            this.dependencies_ci = new HashSet<dependencies_ci>();
            this.dependencies_ci1 = new HashSet<dependencies_ci>();
        }
    
        public string name_ci { get; set; }
        public string description_ci { get; set; }
        public string version_ci { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dependencies_ci> dependencies_ci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dependencies_ci> dependencies_ci1 { get; set; }
    }
}
